"""add core data model tables

Revision ID: 391a1a7fcd55
Revises: 332b6130d461
Create Date: 2026-08-24 10:03:12.321838

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "391a1a7fcd55"
down_revision: str | Sequence[str] | None = "332b6130d461"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_services_name"), "services", ["name"], unique=True)
    op.create_table(
        "deployments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployments_deployed_at"), "deployments", ["deployed_at"], unique=False
    )
    op.create_index(
        "ix_deployments_service_id_deployed_at",
        "deployments",
        ["service_id", "deployed_at"],
        unique=False,
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "P1",
                "P2",
                "P3",
                "P4",
                name="incident_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "detected",
                "triaging",
                "investigating",
                "diagnosed",
                "awaiting_approval",
                "executing",
                "verifying",
                "resolved",
                "manual_intervention_required",
                name="incident_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="detected",
            nullable=False,
        ),
        sa.Column("failure_type", sa.String(length=100), nullable=False),
        sa.Column("root_cause_category", sa.String(length=100), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scenario_seed", sa.Integer(), nullable=True),
        sa.Column("scenario_instance_index", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incidents_detected_at"), "incidents", ["detected_at"], unique=False)
    op.create_index(
        op.f("ix_incidents_root_cause_category"), "incidents", ["root_cause_category"], unique=False
    )
    op.create_index(
        "ix_incidents_scenario_provenance",
        "incidents",
        ["failure_type", "scenario_seed", "scenario_instance_index"],
        unique=False,
    )
    op.create_index(
        "ix_incidents_service_id_detected_at",
        "incidents",
        ["service_id", "detected_at"],
        unique=False,
    )
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "info",
                "warn",
                "error",
                name="log_level",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=2000), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_log_entries_level"), "log_entries", ["level"], unique=False)
    op.create_index(
        "ix_log_entries_service_id_timestamp",
        "log_entries",
        ["service_id", "timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_log_entries_timestamp"), "log_entries", ["timestamp"], unique=False)
    op.create_table(
        "metric_points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metric_points_metric_name"), "metric_points", ["metric_name"], unique=False
    )
    op.create_index(
        "ix_metric_points_service_id_metric_name_timestamp",
        "metric_points",
        ["service_id", "metric_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_metric_points_service_id_timestamp",
        "metric_points",
        ["service_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_points_timestamp"), "metric_points", ["timestamp"], unique=False
    )
    op.create_table(
        "traces_lite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("span_name", sa.String(length=200), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("downstream_service_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["downstream_service_id"], ["services.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_traces_lite_downstream_service_id"),
        "traces_lite",
        ["downstream_service_id"],
        unique=False,
    )
    op.create_index(
        "ix_traces_lite_service_id_timestamp",
        "traces_lite",
        ["service_id", "timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_traces_lite_timestamp"), "traces_lite", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_traces_lite_timestamp"), table_name="traces_lite")
    op.drop_index("ix_traces_lite_service_id_timestamp", table_name="traces_lite")
    op.drop_index(op.f("ix_traces_lite_downstream_service_id"), table_name="traces_lite")
    op.drop_table("traces_lite")
    op.drop_index(op.f("ix_metric_points_timestamp"), table_name="metric_points")
    op.drop_index("ix_metric_points_service_id_timestamp", table_name="metric_points")
    op.drop_index("ix_metric_points_service_id_metric_name_timestamp", table_name="metric_points")
    op.drop_index(op.f("ix_metric_points_metric_name"), table_name="metric_points")
    op.drop_table("metric_points")
    op.drop_index(op.f("ix_log_entries_timestamp"), table_name="log_entries")
    op.drop_index("ix_log_entries_service_id_timestamp", table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_level"), table_name="log_entries")
    op.drop_table("log_entries")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index("ix_incidents_service_id_detected_at", table_name="incidents")
    op.drop_index("ix_incidents_scenario_provenance", table_name="incidents")
    op.drop_index(op.f("ix_incidents_root_cause_category"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_detected_at"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_deployments_service_id_deployed_at", table_name="deployments")
    op.drop_index(op.f("ix_deployments_deployed_at"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_services_name"), table_name="services")
    op.drop_table("services")
    # ### end Alembic commands ###
