"""add node progress events table

Revision ID: 4ba9747722b8
Revises: ce1eb026a432
Create Date: 2026-08-26 13:11:58.096424

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ba9747722b8"
down_revision: str | Sequence[str] | None = "ce1eb026a432"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_progress_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("node_name", sa.String(length=100), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_node_progress_events_incident_id_started_at",
        "node_progress_events",
        ["incident_id", "started_at"],
        unique=False,
    )
    # NOTE: autogenerate also proposed dropping the pre-existing
    # audit_decision_status/audit_execution_outcome/audit_risk_classification/
    # incident_severity/incident_status/log_level CHECK constraints here.
    # That's the same known cosmetic noise documented in alembic/env.py and
    # ce1eb026a432 (the Enum(native_enum=False) comparator can't match its
    # rendered constraint text against the introspected DB constraint) --
    # those constraints are unrelated to this migration and were stripped.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_node_progress_events_incident_id_started_at", table_name="node_progress_events"
    )
    op.drop_table("node_progress_events")
    # ### end Alembic commands ###
