"""add audit trail table

Revision ID: ce1eb026a432
Revises: 391a1a7fcd55
Create Date: 2026-08-24 19:29:38.015455

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce1eb026a432"
down_revision: str | Sequence[str] | None = "391a1a7fcd55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column(
            "risk_classification",
            sa.Enum(
                "safe",
                "high_impact",
                name="audit_risk_classification",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "decision_status",
            sa.Enum(
                "pending_approval",
                "approved",
                "rejected",
                "auto_executed",
                "executed",
                name="audit_decision_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("approver", sa.String(length=200), nullable=True),
        sa.Column(
            "recommended_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "execution_outcome",
            sa.Enum(
                "recovered",
                "still_degraded",
                name="audit_execution_outcome",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("execution_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_decision_status"), "audit_events", ["decision_status"], unique=False
    )
    op.create_index(
        "ix_audit_events_incident_id_recommended_at",
        "audit_events",
        ["incident_id", "recommended_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_risk_classification"),
        "audit_events",
        ["risk_classification"],
        unique=False,
    )
    # NOTE: autogenerate also proposed dropping the pre-existing
    # incident_severity/incident_status/log_level CHECK constraints here.
    # That's the known cosmetic noise documented in alembic/env.py (the
    # Enum(native_enum=False) comparator can't match its rendered
    # constraint text against the introspected DB constraint) — those
    # constraints are unrelated to this migration and were stripped.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_events_risk_classification"), table_name="audit_events")
    op.drop_index("ix_audit_events_incident_id_recommended_at", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_decision_status"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
